const SESSION_STATUS = {
    CREATED: 'CREATED',
    ACTIVE: 'ACTIVE',
    ENDED: 'ENDED',
    ABANDONED: 'ABANDONED',
};

const EVALUATION_STATUS = {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
};

export { SESSION_STATUS, EVALUATION_STATUS };
